### ISSUE TITLE
Data w wiadomościach

### ISSUE THREAD

**Issue by delrisu** [delrisu/IRC#4]
Jeśli możesz wysyłaj razem z wiadomością datę serwera.

Ref:
![image](https://user-images.githubusercontent.com/36968899/68552885-82e71880-041c-11ea-837b-779d1d924a52.png)

**Comment by delrisu** [comment]
https://stackoverflow.com/questions/16357999/current-date-and-time-as-string

**Comment by Ruufuus** [comment]
Done
