### ISSUE TITLE
Nazwa pokoju

### ISSUE THREAD

**Issue by delrisu** [delrisu/IRC#8]
Użytkownik nie może wpisać nazwy pokoju zawierającej spacje:
![image](https://user-images.githubusercontent.com/36968899/69870546-80a40b80-12b0-11ea-9bb9-579be09187b4.png)
efekt:
![image](https://user-images.githubusercontent.com/36968899/69870551-87328300-12b0-11ea-9501-5375d98e8a10.png)

Ale podstawowy pokój servera nazywa się "Default Room"
![image](https://user-images.githubusercontent.com/36968899/69870600-adf0b980-12b0-11ea-8b81-fe1f8a1b1c6e.png)
co powoduje błędy przy wyświetlaniu listy.

Rozwiązanie:
a. Dodaj możliwość definiowania nazw ze spacjami i zmień formatowanie odpowiedzi na $room_list
b. Usuń spację z podstawowej nazwy pokoju.

**Comment by Ruufuus** [comment]
b) jest na branchu Server, testnij

**Comment by delrisu** [comment]
jest ok
